
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   
timeout: 1200s
images:
  - 'us-central1-docker.pkg.dev/gcp-praticals/artifactnewrep'
